### ISSUE TITLE
Explore if NAPSA contribs are always a fixed amount.

### ISSUE THREAD

**Issue by twmbx** [twmbx/zambia-income-tax-calc#2]
@k9uma regarding #1 , are NAPSA deductions always fixed? (really not sure about this and have not bothered to look it up at this point).
If not, may be a need for a future enhancement.

**Comment by k9uma** [comment]
They are fixed at 5%. also now there is the National Health Insurance which is 1% or 2%, not too sure about it

**Comment by Chingaipe** [comment]
NAPSA is fixed at 5% but has a ceiling that should not be exceeded. (not sure what the ceiling is but I know there's a ceiling)
NHI is taxed a 1%

**Comment by twmbx** [comment]
Thanks for the input @Chingaipe & @k9uma. I'll section off some time to update this repo.

@Chingaipe I see something about Flutter in your bio, would you be interested in workign on a Flutter solution for this same concept? Maybe dm me on twitter or send me an email?

**Comment by Chingaipe** [comment]
Sure thing

**Comment by twmbx** [comment]
Closed by [a10f63a](https://github.com/twmbx/zambia-income-tax-calc/commit/a10f63af7e77144004757510e330412eec8f0fbb).
